# Tutorial https://sarunw.com/posts/github-actions-for-ios-projects/
# Caching https://sarunw.com/tips/caching-dependencies-in-github-actions/

name: Checking Estates

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 5-18 * * *'

jobs:
  build:
    name: Run
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Sreality Stochov
        run: usr/local/bin/EstatesChecker --slack-url ${{ secrets.SLACK_WEBHOOK_ESTATES_STOCHOV }} --provider sreality --region Stochov
      - name: Run BezRealitky Stochov
        run: usr/local/bin/EstatesChecker --slack-url ${{ secrets.SLACK_WEBHOOK_ESTATES_STOCHOV }} --provider bezrealitky --region Stochov
      - name: Commit Changes      
        run: git config user.email "jcislinsky@gmail.com"; git add .; if [ $((`git diff --cached --numstat | wc -l`)) -gt 0 ]; then git commit -m "Run"; fi
      - name: Push
        run: git push "https://${{ github.actor }}:${{ secrets.JCISLINSKY_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:master
      
